import 'dart:math';
import 'package:stryde_guest_app/shared/app_graphics.dart';

class AirportVehicleSelection {
  final String carImagePath;
  final String manufacturerName;
  final String modelName;
  final String vehicleClass;
  final String vehicleYear;
  final double reviewCountAverage;
  final int rentalRate;

  AirportVehicleSelection({
    required this.carImagePath,
    required this.manufacturerName,
    required this.modelName,
    required this.vehicleClass,
    required this.vehicleYear,
    required this.reviewCountAverage,
    required this.rentalRate,
  });
}

final _random = Random();

String getRandomCarImage() {
  final carImages = [
    AppGraphics.carPlOne,
    AppGraphics.carPlTwo,
    AppGraphics.carPlThree,
  ];
  return carImages[_random.nextInt(carImages.length)];
}

int getRandomRentalRate() {
  return 50000 + _random.nextInt(49000);
}

double getRandomReviewCountAverage() {
  double randomDouble = (_random.nextDouble() * 2.0) + 3.0;
  return double.parse(randomDouble.toStringAsFixed(1));
}

String getRandomVehicleClass() {
  final vehicleClasses = ['SUV', 'Sedan', 'Van', 'Armored', 'Elite'];
  return vehicleClasses[_random.nextInt(vehicleClasses.length)];
}

String getRandomVehicleYear() {
  return (2006 + _random.nextInt(19)).toString();
}

List<AirportVehicleSelection> airportVehicleSelections = [
  AirportVehicleSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Toyota",
    modelName: "Camry",
    vehicleClass: getRandomVehicleClass(),
    vehicleYear: getRandomVehicleYear(),
    reviewCountAverage: getRandomReviewCountAverage(),
    rentalRate: getRandomRentalRate(),
  ),
  AirportVehicleSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "BMW",
    modelName: "4 Series",
    vehicleClass: getRandomVehicleClass(),
    vehicleYear: getRandomVehicleYear(),
    reviewCountAverage: getRandomReviewCountAverage(),
    rentalRate: getRandomRentalRate(),
  ),
  AirportVehicleSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Mercedes-Benz",
    modelName: "C-Class",
    vehicleClass: getRandomVehicleClass(),
    vehicleYear: getRandomVehicleYear(),
    reviewCountAverage: getRandomReviewCountAverage(),
    rentalRate: getRandomRentalRate(),
  ),
  AirportVehicleSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Volkswagen",
    modelName: "Golf",
    vehicleClass: getRandomVehicleClass(),
    vehicleYear: getRandomVehicleYear(),
    reviewCountAverage: getRandomReviewCountAverage(),
    rentalRate: getRandomRentalRate(),
  ),
  AirportVehicleSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Subaru",
    modelName: "Outback",
    vehicleClass: getRandomVehicleClass(),
    vehicleYear: getRandomVehicleYear(),
    reviewCountAverage: getRandomReviewCountAverage(),
    rentalRate: getRandomRentalRate(),
  ),
  AirportVehicleSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Jeep",
    modelName: "Grand Cherokee",
    vehicleClass: getRandomVehicleClass(),
    vehicleYear: getRandomVehicleYear(),
    reviewCountAverage: getRandomReviewCountAverage(),
    rentalRate: getRandomRentalRate(),
  ),
  AirportVehicleSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Honda",
    modelName: "CR-V",
    vehicleClass: getRandomVehicleClass(),
    vehicleYear: getRandomVehicleYear(),
    reviewCountAverage: getRandomReviewCountAverage(),
    rentalRate: getRandomRentalRate(),
  ),
  AirportVehicleSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Chrysler",
    modelName: "Pacifica",
    vehicleClass: getRandomVehicleClass(),
    vehicleYear: getRandomVehicleYear(),
    reviewCountAverage: getRandomReviewCountAverage(),
    rentalRate: getRandomRentalRate(),
  ),
  AirportVehicleSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Ford",
    modelName: "Transit",
    vehicleClass: getRandomVehicleClass(),
    vehicleYear: getRandomVehicleYear(),
    reviewCountAverage: getRandomReviewCountAverage(),
    rentalRate: getRandomRentalRate(),
  ),
  AirportVehicleSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Ford",
    modelName: "F-150",
    vehicleClass: getRandomVehicleClass(),
    vehicleYear: getRandomVehicleYear(),
    reviewCountAverage: getRandomReviewCountAverage(),
    rentalRate: getRandomRentalRate(),
  ),
  AirportVehicleSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Fiat",
    modelName: "500",
    vehicleClass: getRandomVehicleClass(),
    vehicleYear: getRandomVehicleYear(),
    reviewCountAverage: getRandomReviewCountAverage(),
    rentalRate: getRandomRentalRate(),
  ),
  AirportVehicleSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Mazda",
    modelName: "MX-5 Miata",
    vehicleClass: getRandomVehicleClass(),
    vehicleYear: getRandomVehicleYear(),
    reviewCountAverage: getRandomReviewCountAverage(),
    rentalRate: getRandomRentalRate(),
  ),
  AirportVehicleSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Mercedes-Benz",
    modelName: "Sprinter",
    vehicleClass: getRandomVehicleClass(),
    vehicleYear: getRandomVehicleYear(),
    reviewCountAverage: getRandomReviewCountAverage(),
    rentalRate: getRandomRentalRate(),
  ),
  AirportVehicleSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Land Rover",
    modelName: "Defender",
    vehicleClass: getRandomVehicleClass(),
    vehicleYear: getRandomVehicleYear(),
    reviewCountAverage: getRandomReviewCountAverage(),
    rentalRate: getRandomRentalRate(),
  ),
  AirportVehicleSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "AM General",
    modelName: "HMMWV",
    vehicleClass: getRandomVehicleClass(),
    vehicleYear: getRandomVehicleYear(),
    reviewCountAverage: getRandomReviewCountAverage(),
    rentalRate: getRandomRentalRate(),
  ),
  AirportVehicleSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Winnebago",
    modelName: "Travato",
    vehicleClass: getRandomVehicleClass(),
    vehicleYear: getRandomVehicleYear(),
    reviewCountAverage: getRandomReviewCountAverage(),
    rentalRate: getRandomRentalRate(),
  ),
  AirportVehicleSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Lincoln",
    modelName: "Navigator",
    vehicleClass: getRandomVehicleClass(),
    vehicleYear: getRandomVehicleYear(),
    reviewCountAverage: getRandomReviewCountAverage(),
    rentalRate: getRandomRentalRate(),
  ),
  AirportVehicleSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Isuzu",
    modelName: "N-Series",
    vehicleClass: getRandomVehicleClass(),
    vehicleYear: getRandomVehicleYear(),
    reviewCountAverage: getRandomReviewCountAverage(),
    rentalRate: getRandomRentalRate(),
  ),
  AirportVehicleSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Toyota",
    modelName: "Yaris",
    vehicleClass: getRandomVehicleClass(),
    vehicleYear: getRandomVehicleYear(),
    reviewCountAverage: getRandomReviewCountAverage(),
    rentalRate: getRandomRentalRate(),
  ),
  AirportVehicleSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Hyundai",
    modelName: "Elantra",
    vehicleClass: getRandomVehicleClass(),
    vehicleYear: getRandomVehicleYear(),
    reviewCountAverage: getRandomReviewCountAverage(),
    rentalRate: getRandomRentalRate(),
  ),
  AirportVehicleSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Chevrolet",
    modelName: "Corvette",
    vehicleClass: getRandomVehicleClass(),
    vehicleYear: getRandomVehicleYear(),
    reviewCountAverage: getRandomReviewCountAverage(),
    rentalRate: getRandomRentalRate(),
  ),
  AirportVehicleSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Mazda",
    modelName: "MX-5 Miata RF",
    vehicleClass: getRandomVehicleClass(),
    vehicleYear: getRandomVehicleYear(),
    reviewCountAverage: getRandomReviewCountAverage(),
    rentalRate: getRandomRentalRate(),
  ),
  AirportVehicleSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Mini",
    modelName: "Cooper",
    vehicleClass: getRandomVehicleClass(),
    vehicleYear: getRandomVehicleYear(),
    reviewCountAverage: getRandomReviewCountAverage(),
    rentalRate: getRandomRentalRate(),
  ),
  AirportVehicleSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Volvo",
    modelName: "V60",
    vehicleClass: getRandomVehicleClass(),
    vehicleYear: getRandomVehicleYear(),
    reviewCountAverage: getRandomReviewCountAverage(),
    rentalRate: getRandomRentalRate(),
  ),
  AirportVehicleSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Ford",
    modelName: "Explorer",
    vehicleClass: getRandomVehicleClass(),
    vehicleYear: getRandomVehicleYear(),
    reviewCountAverage: getRandomReviewCountAverage(),
    rentalRate: getRandomRentalRate(),
  ),
  AirportVehicleSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Hyundai",
    modelName: "Tucson",
    vehicleClass: getRandomVehicleClass(),
    vehicleYear: getRandomVehicleYear(),
    reviewCountAverage: getRandomReviewCountAverage(),
    rentalRate: getRandomRentalRate(),
  ),
  AirportVehicleSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Toyota",
    modelName: "Sienna",
    vehicleClass: getRandomVehicleClass(),
    vehicleYear: getRandomVehicleYear(),
    reviewCountAverage: getRandomReviewCountAverage(),
    rentalRate: getRandomRentalRate(),
  ),
  AirportVehicleSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Mercedes-Benz",
    modelName: "Metris",
    vehicleClass: getRandomVehicleClass(),
    vehicleYear: getRandomVehicleYear(),
    reviewCountAverage: getRandomReviewCountAverage(),
    rentalRate: getRandomRentalRate(),
  ),
  AirportVehicleSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "RAM",
    modelName: "1500",
    vehicleClass: getRandomVehicleClass(),
    vehicleYear: getRandomVehicleYear(),
    reviewCountAverage: getRandomReviewCountAverage(),
    rentalRate: getRandomRentalRate(),
  ),
  AirportVehicleSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Ford",
    modelName: "Mustang",
    vehicleClass: getRandomVehicleClass(),
    vehicleYear: getRandomVehicleYear(),
    reviewCountAverage: getRandomReviewCountAverage(),
    rentalRate: getRandomRentalRate(),
  ),
  AirportVehicleSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Chevrolet",
    modelName: "Camaro",
    vehicleClass: getRandomVehicleClass(),
    vehicleYear: getRandomVehicleYear(),
    reviewCountAverage: getRandomReviewCountAverage(),
    rentalRate: getRandomRentalRate(),
  ),
  AirportVehicleSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Honda",
    modelName: "Civic",
    vehicleClass: getRandomVehicleClass(),
    vehicleYear: getRandomVehicleYear(),
    reviewCountAverage: getRandomReviewCountAverage(),
    rentalRate: getRandomRentalRate(),
  ),
  AirportVehicleSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Volvo",
    modelName: "V90",
    vehicleClass: getRandomVehicleClass(),
    vehicleYear: getRandomVehicleYear(),
    reviewCountAverage: getRandomReviewCountAverage(),
    rentalRate: getRandomRentalRate(),
  ),
  AirportVehicleSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Toyota",
    modelName: "Land Cruiser",
    vehicleClass: getRandomVehicleClass(),
    vehicleYear: getRandomVehicleYear(),
    reviewCountAverage: getRandomReviewCountAverage(),
    rentalRate: getRandomRentalRate(),
  ),
  AirportVehicleSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Subaru",
    modelName: "Outback",
    vehicleClass: getRandomVehicleClass(),
    vehicleYear: getRandomVehicleYear(),
    reviewCountAverage: getRandomReviewCountAverage(),
    rentalRate: getRandomRentalRate(),
  ),
  AirportVehicleSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Chrysler",
    modelName: "Pacifica",
    vehicleClass: getRandomVehicleClass(),
    vehicleYear: getRandomVehicleYear(),
    reviewCountAverage: getRandomReviewCountAverage(),
    rentalRate: getRandomRentalRate(),
  ),
  AirportVehicleSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "RAM",
    modelName: "1500",
    vehicleClass: getRandomVehicleClass(),
    vehicleYear: getRandomVehicleYear(),
    reviewCountAverage: getRandomReviewCountAverage(),
    rentalRate: getRandomRentalRate(),
  ),
  AirportVehicleSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Fiat",
    modelName: "500",
    vehicleClass: getRandomVehicleClass(),
    vehicleYear: getRandomVehicleYear(),
    reviewCountAverage: getRandomReviewCountAverage(),
    rentalRate: getRandomRentalRate(),
  ),
  AirportVehicleSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Mazda",
    modelName: "MX-5 Miata",
    vehicleClass: getRandomVehicleClass(),
    vehicleYear: getRandomVehicleYear(),
    reviewCountAverage: getRandomReviewCountAverage(),
    rentalRate: getRandomRentalRate(),
  ),
  AirportVehicleSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Audi",
    modelName: "A4",
    vehicleClass: getRandomVehicleClass(),
    vehicleYear: getRandomVehicleYear(),
    reviewCountAverage: getRandomReviewCountAverage(),
    rentalRate: getRandomRentalRate(),
  ),
  AirportVehicleSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "BMW",
    modelName: "Z4",
    vehicleClass: getRandomVehicleClass(),
    vehicleYear: getRandomVehicleYear(),
    reviewCountAverage: getRandomReviewCountAverage(),
    rentalRate: getRandomRentalRate(),
  ),
  AirportVehicleSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Nissan",
    modelName: "Altima",
    vehicleClass: getRandomVehicleClass(),
    vehicleYear: getRandomVehicleYear(),
    reviewCountAverage: getRandomReviewCountAverage(),
    rentalRate: getRandomRentalRate(),
  ),
  AirportVehicleSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Hyundai",
    modelName: "Tucson",
    vehicleClass: getRandomVehicleClass(),
    vehicleYear: getRandomVehicleYear(),
    reviewCountAverage: getRandomReviewCountAverage(),
    rentalRate: getRandomRentalRate(),
  ),
  AirportVehicleSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Jeep",
    modelName: "Wrangler",
    vehicleClass: getRandomVehicleClass(),
    vehicleYear: getRandomVehicleYear(),
    reviewCountAverage: getRandomReviewCountAverage(),
    rentalRate: getRandomRentalRate(),
  ),
  AirportVehicleSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Porsche",
    modelName: "911",
    vehicleClass: getRandomVehicleClass(),
    vehicleYear: getRandomVehicleYear(),
    reviewCountAverage: getRandomReviewCountAverage(),
    rentalRate: getRandomRentalRate(),
  ),
  AirportVehicleSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Land Rover",
    modelName: "Range Rover",
    vehicleClass: getRandomVehicleClass(),
    vehicleYear: getRandomVehicleYear(),
    reviewCountAverage: getRandomReviewCountAverage(),
    rentalRate: getRandomRentalRate(),
  ),
  AirportVehicleSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Tesla",
    modelName: "Model S",
    vehicleClass: getRandomVehicleClass(),
    vehicleYear: getRandomVehicleYear(),
    reviewCountAverage: getRandomReviewCountAverage(),
    rentalRate: getRandomRentalRate(),
  ),
  AirportVehicleSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Buick",
    modelName: "Enclave",
    vehicleClass: getRandomVehicleClass(),
    vehicleYear: getRandomVehicleYear(),
    reviewCountAverage: getRandomReviewCountAverage(),
    rentalRate: getRandomRentalRate(),
  ),
  AirportVehicleSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Lexus",
    modelName: "RX",
    vehicleClass: getRandomVehicleClass(),
    vehicleYear: getRandomVehicleYear(),
    reviewCountAverage: getRandomReviewCountAverage(),
    rentalRate: getRandomRentalRate(),
  ),
];