import 'dart:math';
import 'package:stryde_guest_app/shared/app_graphics.dart';

class RentalSelection {
  final String carImagePath;
  final String manufacturerName;
  final String modelName;
  final String vehicleBodyType;
  final double reviewCountAverage;
  final int dailyRentalRate;

  RentalSelection({
    required this.carImagePath,
    required this.manufacturerName,
    required this.modelName,
    required this.vehicleBodyType,
    required this.reviewCountAverage,
    required this.dailyRentalRate,
  });
}

final _random = Random();

String getRandomCarImage() {
  final carImages = [
    AppGraphics.carPlOne,
    AppGraphics.carPlTwo,
    AppGraphics.carPlThree,
  ];
  return carImages[_random.nextInt(carImages.length)];
}

int getRandomDailyRentalRate() {
  return 50000 + _random.nextInt(49000);
}

double getRandomReviewCountAverage() {
  // Generate a random double between 3.0 and 5.0
  double randomDouble = (_random.nextDouble() * 2.0) + 3.0;
  // Round the number to one decimal place and ensure it is less than 5
  return double.parse(randomDouble.toStringAsFixed(1));
}

List<RentalSelection> rentalSelections = [
  RentalSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Toyota",
    modelName: "Camry",
    vehicleBodyType: "Sedan",
    reviewCountAverage: getRandomReviewCountAverage(),
    dailyRentalRate: getRandomDailyRentalRate(),
  ),
  RentalSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "BMW",
    modelName: "4 Series",
    vehicleBodyType: "Coupe",
    reviewCountAverage: getRandomReviewCountAverage(),
    dailyRentalRate: getRandomDailyRentalRate(),
  ),
  RentalSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Mercedes-Benz",
    modelName: "C-Class Cabriolet",
    vehicleBodyType: "Convertible",
    reviewCountAverage: getRandomReviewCountAverage(),
    dailyRentalRate: getRandomDailyRentalRate(),
  ),
  RentalSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Volkswagen",
    modelName: "Golf",
    vehicleBodyType: "Hatchback",
    reviewCountAverage: getRandomReviewCountAverage(),
    dailyRentalRate: getRandomDailyRentalRate(),
  ),
  RentalSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Subaru",
    modelName: "Outback",
    vehicleBodyType: "Station Wagon",
    reviewCountAverage: getRandomReviewCountAverage(),
    dailyRentalRate: getRandomDailyRentalRate(),
  ),
  RentalSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Jeep",
    modelName: "Grand Cherokee",
    vehicleBodyType: "SUV (Sport Utility Vehicle)",
    reviewCountAverage: getRandomReviewCountAverage(),
    dailyRentalRate: getRandomDailyRentalRate(),
  ),
  RentalSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Honda",
    modelName: "CR-V",
    vehicleBodyType: "Crossover",
    reviewCountAverage: getRandomReviewCountAverage(),
    dailyRentalRate: getRandomDailyRentalRate(),
  ),
  RentalSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Chrysler",
    modelName: "Pacifica",
    vehicleBodyType: "Minivan",
    reviewCountAverage: getRandomReviewCountAverage(),
    dailyRentalRate: getRandomDailyRentalRate(),
  ),
  RentalSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Ford",
    modelName: "Transit",
    vehicleBodyType: "Van",
    reviewCountAverage: getRandomReviewCountAverage(),
    dailyRentalRate: getRandomDailyRentalRate(),
  ),
  RentalSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Ford",
    modelName: "F-150",
    vehicleBodyType: "Pickup Truck",
    reviewCountAverage: getRandomReviewCountAverage(),
    dailyRentalRate: getRandomDailyRentalRate(),
  ),
  RentalSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Fiat",
    modelName: "500",
    vehicleBodyType: "Microcar",
    reviewCountAverage: getRandomReviewCountAverage(),
    dailyRentalRate: getRandomDailyRentalRate(),
  ),
  RentalSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Mazda",
    modelName: "MX-5 Miata",
    vehicleBodyType: "Roadster",
    reviewCountAverage: getRandomReviewCountAverage(),
    dailyRentalRate: getRandomDailyRentalRate(),
  ),
  RentalSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Mercedes-Benz",
    modelName: "Sprinter",
    vehicleBodyType: "Panel Van",
    reviewCountAverage: getRandomReviewCountAverage(),
    dailyRentalRate: getRandomDailyRentalRate(),
  ),
  RentalSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Land Rover",
    modelName: "Defender",
    vehicleBodyType: "Off-Road Vehicle",
    reviewCountAverage: getRandomReviewCountAverage(),
    dailyRentalRate: getRandomDailyRentalRate(),
  ),
  RentalSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "AM General",
    modelName: "HMMWV",
    vehicleBodyType: "Military Vehicle",
    reviewCountAverage: getRandomReviewCountAverage(),
    dailyRentalRate: getRandomDailyRentalRate(),
  ),
  RentalSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Winnebago",
    modelName: "Travato",
    vehicleBodyType: "RV (Recreational Vehicle)",
    reviewCountAverage: getRandomReviewCountAverage(),
    dailyRentalRate: getRandomDailyRentalRate(),
  ),
  RentalSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Lincoln",
    modelName: "Navigator",
    vehicleBodyType: "Limousine",
    reviewCountAverage: getRandomReviewCountAverage(),
    dailyRentalRate: getRandomDailyRentalRate(),
  ),
  RentalSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Isuzu",
    modelName: "N-Series",
    vehicleBodyType: "Box Truck",
    reviewCountAverage: getRandomReviewCountAverage(),
    dailyRentalRate: getRandomDailyRentalRate(),
  ),
  RentalSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Toyota",
    modelName: "Yaris",
    vehicleBodyType: "Sedan",
    reviewCountAverage: getRandomReviewCountAverage(),
    dailyRentalRate: getRandomDailyRentalRate(),
  ),
  RentalSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Hyundai",
    modelName: "Elantra",
    vehicleBodyType: "Sedan",
    reviewCountAverage: getRandomReviewCountAverage(),
    dailyRentalRate: getRandomDailyRentalRate(),
  ),
  RentalSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Chevrolet",
    modelName: "Corvette",
    vehicleBodyType: "Coupe",
    reviewCountAverage: getRandomReviewCountAverage(),
    dailyRentalRate: getRandomDailyRentalRate(),
  ),
  RentalSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Mazda",
    modelName: "MX-5 Miata RF",
    vehicleBodyType: "Convertible",
    reviewCountAverage: getRandomReviewCountAverage(),
    dailyRentalRate: getRandomDailyRentalRate(),
  ),
  RentalSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Mini",
    modelName: "Cooper",
    vehicleBodyType: "Hatchback",
    reviewCountAverage: getRandomReviewCountAverage(),
    dailyRentalRate: getRandomDailyRentalRate(),
  ),
  RentalSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Volvo",
    modelName: "V60",
    vehicleBodyType: "Station Wagon",
    reviewCountAverage: getRandomReviewCountAverage(),
    dailyRentalRate: getRandomDailyRentalRate(),
  ),
  RentalSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Ford",
    modelName: "Explorer",
    vehicleBodyType: "SUV (Sport Utility Vehicle)",
    reviewCountAverage: getRandomReviewCountAverage(),
    dailyRentalRate: getRandomDailyRentalRate(),
  ),
  RentalSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Hyundai",
    modelName: "Tucson",
    vehicleBodyType: "Crossover",
    reviewCountAverage: getRandomReviewCountAverage(),
    dailyRentalRate: getRandomDailyRentalRate(),
  ),
  RentalSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Toyota",
    modelName: "Sienna",
    vehicleBodyType: "Minivan",
    reviewCountAverage: getRandomReviewCountAverage(),
    dailyRentalRate: getRandomDailyRentalRate(),
  ),
  RentalSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Mercedes-Benz",
    modelName: "Metris",
    vehicleBodyType: "Van",
    reviewCountAverage: getRandomReviewCountAverage(),
    dailyRentalRate: getRandomDailyRentalRate(),
  ),
  RentalSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "RAM",
    modelName: "1500",
    vehicleBodyType: "Pickup Truck",
    reviewCountAverage: getRandomReviewCountAverage(),
    dailyRentalRate: getRandomDailyRentalRate(),
  ),
  RentalSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Ford",
    modelName: "Mustang",
    vehicleBodyType: "Coupe",
    reviewCountAverage: getRandomReviewCountAverage(),
    dailyRentalRate: getRandomDailyRentalRate(),
  ),
  RentalSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Chevrolet",
    modelName: "Camaro",
    vehicleBodyType: "Convertible",
    reviewCountAverage: getRandomReviewCountAverage(),
    dailyRentalRate: getRandomDailyRentalRate(),
  ),
  RentalSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Honda",
    modelName: "Civic",
    vehicleBodyType: "Hatchback",
    reviewCountAverage: getRandomReviewCountAverage(),
    dailyRentalRate: getRandomDailyRentalRate(),
  ),
  RentalSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Volvo",
    modelName: "V90",
    vehicleBodyType: "Station Wagon",
    reviewCountAverage: getRandomReviewCountAverage(),
    dailyRentalRate: getRandomDailyRentalRate(),
  ),
  RentalSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Toyota",
    modelName: "Land Cruiser",
    vehicleBodyType: "SUV (Sport Utility Vehicle)",
    reviewCountAverage: getRandomReviewCountAverage(),
    dailyRentalRate: getRandomDailyRentalRate(),
  ),
  RentalSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Subaru",
    modelName: "Outback",
    vehicleBodyType: "Crossover",
    reviewCountAverage: getRandomReviewCountAverage(),
    dailyRentalRate: getRandomDailyRentalRate(),
  ),
  RentalSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Chrysler",
    modelName: "Pacifica",
    vehicleBodyType: "Minivan",
    reviewCountAverage: getRandomReviewCountAverage(),
    dailyRentalRate: getRandomDailyRentalRate(),
  ),
  RentalSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "RAM",
    modelName: "1500",
    vehicleBodyType: "Pickup Truck",
    reviewCountAverage: getRandomReviewCountAverage(),
    dailyRentalRate: getRandomDailyRentalRate(),
  ),
  RentalSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Fiat",
    modelName: "500",
    vehicleBodyType: "Microcar",
    reviewCountAverage: getRandomReviewCountAverage(),
    dailyRentalRate: getRandomDailyRentalRate(),
  ),
  RentalSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Mazda",
    modelName: "MX-5 Miata",
    vehicleBodyType: "Roadster",
    reviewCountAverage: getRandomReviewCountAverage(),
    dailyRentalRate: getRandomDailyRentalRate(),
  ),
  RentalSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Audi",
    modelName: "A4",
    vehicleBodyType: "Sedan",
    reviewCountAverage: getRandomReviewCountAverage(),
    dailyRentalRate: getRandomDailyRentalRate(),
  ),
  RentalSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "BMW",
    modelName: "Z4",
    vehicleBodyType: "Convertible",
    reviewCountAverage: getRandomReviewCountAverage(),
    dailyRentalRate: getRandomDailyRentalRate(),
  ),
  RentalSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Nissan",
    modelName: "Altima",
    vehicleBodyType: "Sedan",
    reviewCountAverage: getRandomReviewCountAverage(),
    dailyRentalRate: getRandomDailyRentalRate(),
  ),
  RentalSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Hyundai",
    modelName: "Tucson",
    vehicleBodyType: "SUV (Sport Utility Vehicle)",
    reviewCountAverage: getRandomReviewCountAverage(),
    dailyRentalRate: getRandomDailyRentalRate(),
  ),
  RentalSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Jeep",
    modelName: "Wrangler",
    vehicleBodyType: "Off-Road Vehicle",
    reviewCountAverage: getRandomReviewCountAverage(),
    dailyRentalRate: getRandomDailyRentalRate(),
  ),
  RentalSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Porsche",
    modelName: "911",
    vehicleBodyType: "Coupe",
    reviewCountAverage: getRandomReviewCountAverage(),
    dailyRentalRate: getRandomDailyRentalRate(),
  ),
  RentalSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Land Rover",
    modelName: "Range Rover",
    vehicleBodyType: "SUV (Sport Utility Vehicle)",
    reviewCountAverage: getRandomReviewCountAverage(),
    dailyRentalRate: getRandomDailyRentalRate(),
  ),
  RentalSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Tesla",
    modelName: "Model S",
    vehicleBodyType: "Sedan",
    reviewCountAverage: getRandomReviewCountAverage(),
    dailyRentalRate: getRandomDailyRentalRate(),
  ),
  RentalSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Buick",
    modelName: "Enclave",
    vehicleBodyType: "SUV (Sport Utility Vehicle)",
    reviewCountAverage: getRandomReviewCountAverage(),
    dailyRentalRate: getRandomDailyRentalRate(),
  ),
  RentalSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Lexus",
    modelName: "RX",
    vehicleBodyType: "Crossover",
    reviewCountAverage: getRandomReviewCountAverage(),
    dailyRentalRate: getRandomDailyRentalRate(),
  ),
];
