import 'dart:math';
import 'package:stryde_guest_app/shared/app_graphics.dart';

class RentalSelection {
  final String carImagePath;
  final String manufacturerName;
  final String modelName;
  final String vehicleBodyType;
  final double reviewCountAverage;
  final int dailyRentalRate;

  RentalSelection({
    required this.carImagePath,
    required this.manufacturerName,
    required this.modelName,
    required this.vehicleBodyType,
    required this.reviewCountAverage,
    required this.dailyRentalRate,
  });
}

final _random = Random();

String getRandomCarImage() {
  final carImages = [
    AppGraphics.carPlOne,
    AppGraphics.carPlTwo,
    AppGraphics.carPlThree,
  ];
  return carImages[_random.nextInt(carImages.length)];
}

int getRandomDailyRentalRate() {
  return 50000 + _random.nextInt(49000);
}

double getRandomReviewCountAverage() {
  double randomDouble = (_random.nextDouble() * 2.0) + 3.0;
  return double.parse(randomDouble.toStringAsFixed(1));
}

List<RentalSelection> rentalSelections = [
  RentalSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Toyota",
    modelName: "Camry",
    vehicleBodyType: "Sedan",
    reviewCountAverage: getRandomReviewCountAverage(),
    dailyRentalRate: getRandomDailyRentalRate(),
  ),
  RentalSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "BMW",
    modelName: "4 Series",
    vehicleBodyType: "Coupes & Convertibles",
    reviewCountAverage: getRandomReviewCountAverage(),
    dailyRentalRate: getRandomDailyRentalRate(),
  ),
  RentalSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Mercedes-Benz",
    modelName: "C-Class Cabriolet",
    vehicleBodyType: "Coupes & Convertibles",
    reviewCountAverage: getRandomReviewCountAverage(),
    dailyRentalRate: getRandomDailyRentalRate(),
  ),
  RentalSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Volkswagen",
    modelName: "Golf",
    vehicleBodyType: "Hatchback",
    reviewCountAverage: getRandomReviewCountAverage(),
    dailyRentalRate: getRandomDailyRentalRate(),
  ),
  RentalSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Subaru",
    modelName: "Outback",
    vehicleBodyType: "Station Wagon",
    reviewCountAverage: getRandomReviewCountAverage(),
    dailyRentalRate: getRandomDailyRentalRate(),
  ),
  RentalSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Jeep",
    modelName: "Grand Cherokee",
    vehicleBodyType: "SUV (Sport Utility Vehicle)",
    reviewCountAverage: getRandomReviewCountAverage(),
    dailyRentalRate: getRandomDailyRentalRate(),
  ),
  RentalSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Honda",
    modelName: "CR-V",
    vehicleBodyType: "SUV (Sport Utility Vehicle)",
    reviewCountAverage: getRandomReviewCountAverage(),
    dailyRentalRate: getRandomDailyRentalRate(),
  ),
  RentalSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Chrysler",
    modelName: "Pacifica",
    vehicleBodyType: "Mini-Van",
    reviewCountAverage: getRandomReviewCountAverage(),
    dailyRentalRate: getRandomDailyRentalRate(),
  ),
  RentalSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Ford",
    modelName: "Transit",
    vehicleBodyType: "Van",
    reviewCountAverage: getRandomReviewCountAverage(),
    dailyRentalRate: getRandomDailyRentalRate(),
  ),
  RentalSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Ford",
    modelName: "F-150",
    vehicleBodyType: "Pick-up Truck",
    reviewCountAverage: getRandomReviewCountAverage(),
    dailyRentalRate: getRandomDailyRentalRate(),
  ),
  RentalSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Mercedes-Benz",
    modelName: "Sprinter",
    vehicleBodyType: "Van",
    reviewCountAverage: getRandomReviewCountAverage(),
    dailyRentalRate: getRandomDailyRentalRate(),
  ),
  RentalSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Land Rover",
    modelName: "Defender",
    vehicleBodyType: "SUV (Sport Utility Vehicle)",
    reviewCountAverage: getRandomReviewCountAverage(),
    dailyRentalRate: getRandomDailyRentalRate(),
  ),
  RentalSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Winnebago",
    modelName: "Travato",
    vehicleBodyType: "RV (Recreational Vehicle)",
    reviewCountAverage: getRandomReviewCountAverage(),
    dailyRentalRate: getRandomDailyRentalRate(),
  ),
  RentalSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Lincoln",
    modelName: "Navigator",
    vehicleBodyType: "Limousine",
    reviewCountAverage: getRandomReviewCountAverage(),
    dailyRentalRate: getRandomDailyRentalRate(),
  ),
  RentalSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Chevrolet",
    modelName: "CoRV (Recreational Vehicle)ette",
    vehicleBodyType: "Coupes & Convertibles",
    reviewCountAverage: getRandomReviewCountAverage(),
    dailyRentalRate: getRandomDailyRentalRate(),
  ),
  RentalSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Mazda",
    modelName: "MX-5 Miata RF",
    vehicleBodyType: "Coupes & Convertibles",
    reviewCountAverage: getRandomReviewCountAverage(),
    dailyRentalRate: getRandomDailyRentalRate(),
  ),
  RentalSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Mini",
    modelName: "Cooper",
    vehicleBodyType: "Hatchback",
    reviewCountAverage: getRandomReviewCountAverage(),
    dailyRentalRate: getRandomDailyRentalRate(),
  ),
  RentalSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Volvo",
    modelName: "V60",
    vehicleBodyType: "Station Wagon",
    reviewCountAverage: getRandomReviewCountAverage(),
    dailyRentalRate: getRandomDailyRentalRate(),
  ),
  RentalSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Ford",
    modelName: "Explorer",
    vehicleBodyType: "SUV (Sport Utility Vehicle)",
    reviewCountAverage: getRandomReviewCountAverage(),
    dailyRentalRate: getRandomDailyRentalRate(),
  ),
  RentalSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Hyundai",
    modelName: "Elantra",
    vehicleBodyType: "Sedan",
    reviewCountAverage: getRandomReviewCountAverage(),
    dailyRentalRate: getRandomDailyRentalRate(),
  ),
  RentalSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Toyota",
    modelName: "Land Cruiser",
    vehicleBodyType: "SUV (Sport Utility Vehicle)",
    reviewCountAverage: getRandomReviewCountAverage(),
    dailyRentalRate: getRandomDailyRentalRate(),
  ),
  RentalSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "RAM",
    modelName: "1500",
    vehicleBodyType: "Pick-up Truck",
    reviewCountAverage: getRandomReviewCountAverage(),
    dailyRentalRate: getRandomDailyRentalRate(),
  ),
  RentalSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Toyota",
    modelName: "Sienna",
    vehicleBodyType: "Mini-Van",
    reviewCountAverage: getRandomReviewCountAverage(),
    dailyRentalRate: getRandomDailyRentalRate(),
  ),
  RentalSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Honda",
    modelName: "Civic",
    vehicleBodyType: "Sedan",
    reviewCountAverage: getRandomReviewCountAverage(),
    dailyRentalRate: getRandomDailyRentalRate(),
  ),
  RentalSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Chevrolet",
    modelName: "Camaro",
    vehicleBodyType: "Coupes & Convertibles",
    reviewCountAverage: getRandomReviewCountAverage(),
    dailyRentalRate: getRandomDailyRentalRate(),
  ),
  RentalSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Toyota",
    modelName: "Yaris",
    vehicleBodyType: "Hatchback",
    reviewCountAverage: getRandomReviewCountAverage(),
    dailyRentalRate: getRandomDailyRentalRate(),
  ),
  RentalSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Volvo",
    modelName: "V90",
    vehicleBodyType: "Station Wagon",
    reviewCountAverage: getRandomReviewCountAverage(),
    dailyRentalRate: getRandomDailyRentalRate(),
  ),
  RentalSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Honda",
    modelName: "Pilot",
    vehicleBodyType: "SUV (Sport Utility Vehicle)",
    reviewCountAverage: getRandomReviewCountAverage(),
    dailyRentalRate: getRandomDailyRentalRate(),
  ),
  RentalSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Lexus",
    modelName: "LX",
    vehicleBodyType: "SUV (Sport Utility Vehicle)",
    reviewCountAverage: getRandomReviewCountAverage(),
    dailyRentalRate: getRandomDailyRentalRate(),
  ),
  RentalSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Ford",
    modelName: "Edge",
    vehicleBodyType: "SUV (Sport Utility Vehicle)",
    reviewCountAverage: getRandomReviewCountAverage(),
    dailyRentalRate: getRandomDailyRentalRate(),
  ),
  RentalSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Mazda",
    modelName: "CX-5",
    vehicleBodyType: "SUV (Sport Utility Vehicle)",
    reviewCountAverage: getRandomReviewCountAverage(),
    dailyRentalRate: getRandomDailyRentalRate(),
  ),
  RentalSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Dodge",
    modelName: "Durango",
    vehicleBodyType: "SUV (Sport Utility Vehicle)",
    reviewCountAverage: getRandomReviewCountAverage(),
    dailyRentalRate: getRandomDailyRentalRate(),
  ),
  RentalSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Audi",
    modelName: "A6",
    vehicleBodyType: "Sedan",
    reviewCountAverage: getRandomReviewCountAverage(),
    dailyRentalRate: getRandomDailyRentalRate(),
  ),
  RentalSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "BMW",
    modelName: "X5",
    vehicleBodyType: "SUV (Sport Utility Vehicle)",
    reviewCountAverage: getRandomReviewCountAverage(),
    dailyRentalRate: getRandomDailyRentalRate(),
  ),
  RentalSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Chevrolet",
    modelName: "Suburban",
    vehicleBodyType: "SUV (Sport Utility Vehicle)",
    reviewCountAverage: getRandomReviewCountAverage(),
    dailyRentalRate: getRandomDailyRentalRate(),
  ),
  RentalSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Chevrolet",
    modelName: "Impala",
    vehicleBodyType: "Sedan",
    reviewCountAverage: getRandomReviewCountAverage(),
    dailyRentalRate: getRandomDailyRentalRate(),
  ),
  RentalSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Hyundai",
    modelName: "Santa Fe",
    vehicleBodyType: "SUV (Sport Utility Vehicle)",
    reviewCountAverage: getRandomReviewCountAverage(),
    dailyRentalRate: getRandomDailyRentalRate(),
  ),
  RentalSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Mercedes-Benz",
    modelName: "G-Class",
    vehicleBodyType: "SUV (Sport Utility Vehicle)",
    reviewCountAverage: getRandomReviewCountAverage(),
    dailyRentalRate: getRandomDailyRentalRate(),
  ),
  RentalSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Ford",
    modelName: "Mustang",
    vehicleBodyType: "Coupes & Convertibles",
    reviewCountAverage: getRandomReviewCountAverage(),
    dailyRentalRate: getRandomDailyRentalRate(),
  ),
  RentalSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Jaguar",
    modelName: "F-Type",
    vehicleBodyType: "Coupes & Convertibles",
    reviewCountAverage: getRandomReviewCountAverage(),
    dailyRentalRate: getRandomDailyRentalRate(),
  ),
  RentalSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Lamborghini",
    modelName: "Huracan",
    vehicleBodyType: "Coupes & Convertibles",
    reviewCountAverage: getRandomReviewCountAverage(),
    dailyRentalRate: getRandomDailyRentalRate(),
  ),
  RentalSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Nissan",
    modelName: "Altima",
    vehicleBodyType: "Sedan",
    reviewCountAverage: getRandomReviewCountAverage(),
    dailyRentalRate: getRandomDailyRentalRate(),
  ),
  RentalSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Porsche",
    modelName: "911",
    vehicleBodyType: "Coupes & Convertibles",
    reviewCountAverage: getRandomReviewCountAverage(),
    dailyRentalRate: getRandomDailyRentalRate(),
  ),
  RentalSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Chevrolet",
    modelName: "Traverse",
    vehicleBodyType: "SUV (Sport Utility Vehicle)",
    reviewCountAverage: getRandomReviewCountAverage(),
    dailyRentalRate: getRandomDailyRentalRate(),
  ),
  RentalSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Ford",
    modelName: "Escape",
    vehicleBodyType: "SUV (Sport Utility Vehicle)",
    reviewCountAverage: getRandomReviewCountAverage(),
    dailyRentalRate: getRandomDailyRentalRate(),
  ),
  RentalSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Volkswagen",
    modelName: "Tiguan",
    vehicleBodyType: "SUV (Sport Utility Vehicle)",
    reviewCountAverage: getRandomReviewCountAverage(),
    dailyRentalRate: getRandomDailyRentalRate(),
  ),
  RentalSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Honda",
    modelName: "Accord",
    vehicleBodyType: "Sedan",
    reviewCountAverage: getRandomReviewCountAverage(),
    dailyRentalRate: getRandomDailyRentalRate(),
  ),
  RentalSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Tesla",
    modelName: "Model 3",
    vehicleBodyType: "Sedan",
    reviewCountAverage: getRandomReviewCountAverage(),
    dailyRentalRate: getRandomDailyRentalRate(),
  ),
  RentalSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Hyundai",
    modelName: "Palisade",
    vehicleBodyType: "SUV (Sport Utility Vehicle)",
    reviewCountAverage: getRandomReviewCountAverage(),
    dailyRentalRate: getRandomDailyRentalRate(),
  ),
  RentalSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Chevrolet",
    modelName: "Tahoe",
    vehicleBodyType: "SUV (Sport Utility Vehicle)",
    reviewCountAverage: getRandomReviewCountAverage(),
    dailyRentalRate: getRandomDailyRentalRate(),
  ),
  RentalSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Audi",
    modelName: "Q7",
    vehicleBodyType: "SUV (Sport Utility Vehicle)",
    reviewCountAverage: getRandomReviewCountAverage(),
    dailyRentalRate: getRandomDailyRentalRate(),
  ),
  RentalSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Lexus",
    modelName: "RX",
    vehicleBodyType: "SUV (Sport Utility Vehicle)",
    reviewCountAverage: getRandomReviewCountAverage(),
    dailyRentalRate: getRandomDailyRentalRate(),
  ),
  RentalSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Ford",
    modelName: "Expedition",
    vehicleBodyType: "SUV (Sport Utility Vehicle)",
    reviewCountAverage: getRandomReviewCountAverage(),
    dailyRentalRate: getRandomDailyRentalRate(),
  ),
  RentalSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Cadillac",
    modelName: "Escalade",
    vehicleBodyType: "SUV (Sport Utility Vehicle)",
    reviewCountAverage: getRandomReviewCountAverage(),
    dailyRentalRate: getRandomDailyRentalRate(),
  ),
  RentalSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Honda",
    modelName: "Odyssey",
    vehicleBodyType: "Mini-Van",
    reviewCountAverage: getRandomReviewCountAverage(),
    dailyRentalRate: getRandomDailyRentalRate(),
  ),
  RentalSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Chevrolet",
    modelName: "Blazer",
    vehicleBodyType: "SUV (Sport Utility Vehicle)",
    reviewCountAverage: getRandomReviewCountAverage(),
    dailyRentalRate: getRandomDailyRentalRate(),
  ),
  RentalSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Toyota",
    modelName: "Avalon",
    vehicleBodyType: "Sedan",
    reviewCountAverage: getRandomReviewCountAverage(),
    dailyRentalRate: getRandomDailyRentalRate(),
  ),
  RentalSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "BMW",
    modelName: "5 Series",
    vehicleBodyType: "Sedan",
    reviewCountAverage: getRandomReviewCountAverage(),
    dailyRentalRate: getRandomDailyRentalRate(),
  ),
  RentalSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Toyota",
    modelName: "Highlander",
    vehicleBodyType: "SUV (Sport Utility Vehicle)",
    reviewCountAverage: getRandomReviewCountAverage(),
    dailyRentalRate: getRandomDailyRentalRate(),
  ),
  RentalSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Audi",
    modelName: "A4",
    vehicleBodyType: "Sedan",
    reviewCountAverage: getRandomReviewCountAverage(),
    dailyRentalRate: getRandomDailyRentalRate(),
  ),
  RentalSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Blue Bird",
    modelName: "Vision",
    vehicleBodyType: "Bus",
    reviewCountAverage: getRandomReviewCountAverage(),
    dailyRentalRate: getRandomDailyRentalRate(),
  ),
  RentalSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Thomas Built",
    modelName: "Saf-T-Liner C2",
    vehicleBodyType: "Bus",
    reviewCountAverage: getRandomReviewCountAverage(),
    dailyRentalRate: getRandomDailyRentalRate(),
  ),
  RentalSelection(
    carImagePath: getRandomCarImage(),
    manufacturerName: "Prevost",
    modelName: "X3-45",
    vehicleBodyType: "Bus",
    reviewCountAverage: getRandomReviewCountAverage(),
    dailyRentalRate: getRandomDailyRentalRate(),
  ),
];
